name: Ruby Gem

on:
  shedule:
  - cron: "*/20 * * * *"

jobs:
  build:
    name: awesome_bot test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: set up awesome_bot
      run: |
        gem install awesome_bot

    - name: script
      run: |
        awesome_bot README.md --white-list travis-ci,vimgolf.com
